version: '2.1'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
services:

  nodejs: 
    image: myuserindocker/deployment-environment:latest
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    volumes:
      - ../../source:/app/
    working_dir: /app/
    command: bash -c "sleep 100000000;"

  rethinkdb:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-development}
    working_dir: /
    volumes:
      # volume inside docker-machine not through Windows volume. because it causes problems otherwise.
      - /volume/rethinkdbData:/rethinkdb_data
