version: '2.1'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
services:

  nodejs: 
    image: myuserindocker/deployment-environment:latest
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      # BrowserSync ports:
      - "9901:9901"
      - "9902:9902"
      - "9903:9903"
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-development}
    volumes:
      - ../../source:/project/application/source/
      - ../../setup/build:/project/application/setup/build/
      - ../../distribution:/project/application/distribution/
      - ../../dependency/appDeploymentLifecycle:/project/dependency/appDeploymentLifecycle/
    working_dir: /project/application/source/serverSide/
    command: bash -c "sleep 100000000;"

  rethinkdb:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-development}
    working_dir: /
    volumes:
      # volume inside docker-machine not through Windows volume. because it causes problems otherwise.
      - /mnt/datadisk-1/taleb/rethinkdbData:/data/rethinkdb_data/
