version: '3'

networks: 
  default:
    external: false
  proxy_default:
    external: true

# volumes: 
#   dentrist:
#     driver: rexray

services:

  # internal ports = 80, 443
  nodejs:
    image: myuserindocker/taleb-webapp:latest
    environment:
      DEPLOYMENT: production
      HOST: taleb.io
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - default
      - proxy_default
    # entrypoint: node babelCompile.entrypoint.js
    # command: sleep 100000

  # internal port = 8080
  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - "/mnt/datadisk-1/taleb/rethinkdbData:/data/rethinkdb_data/"
    environment:
      DEPLOYMENT: production
    networks:
      - default
      - proxy_default
