version: '3.3'

networks: 
  default:
    external: false
  proxy:
    external: true

# volumes: 
#   dentrist:
#     driver: rexray

services:

  # https://hub.docker.com/r/myuserindocker/taleb-webapp/tags/
  # internal ports = 80, 443
  nodejs:
    image: myuserindocker/taleb-webapp:latest
    environment:
      DEPLOYMENT: production
      HOST: taleb.io
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - default
      - proxy
  
  # RethinkDB - https://hub.docker.com/r/library/rethinkdb/tags/
  # internal port = 8080
  rethinkdb:
    image: rethinkdb:2.3.6
    volumes:
      - "/mnt/datadisk-1/taleb/rethinkdbData:/data/rethinkdb_data/"
    networks:
      - default
      - proxy
